Assignment3: uvic.disk.DiskScheduler Class Reference
uvic.disk.DiskScheduler Class Reference abstract
The DiskScheduler class acts as a husk class for different disk scheduler implementations.
Public Member Functions
DiskScheduler (int startPosition)
Constructs a Disk class object with specified size and request capacity.
int getTotalBlocks ()
Return the number of blocks in the disk.
int getHeadPos ()
Return the current head position.
void spin (int level)
Starts the disk emulator.
void shutdown ()
Stops the disk emulator.
int read (int position)
Reads the specified block into the specified data buffer.
void write (int position, int value)
Writes a block of data at the specified block.
void run ()
The disk worker thread.
Protected Member Functions
abstract void remove ()
Dequeues the current I/O request and selects the next request for processing.
abstract void insert (DiskRequest dr)
Inserts a new request into the wait queue.
void seek (int position)
This method forces the disk head to seek to the specified position.
void showQ ()
debugging method for displaying list of live requests.
Protected Attributes
DiskRequest current = null
The currently scheduled disk request.
int blockCnt = 0
Additional Inherited Members
Static Public Member Functions inherited from uvic.disk.Disk
static void save (int id)
Save the current disk to file with identifer id.
static void load (int id)
Load the contents of the file with identifer id into the disk.
static native void save_disk (int id, int[] buffer, int len)
static native void load_disk (int id, int[] buffer, int len)
Static Public Attributes inherited from uvic.posix.Thread
static final int SYSTEM = 0
FCFS.
static final int REAL_TIME = 1
Round-robin (quantum = 1)
static final int USER = 2
Round-robin (quantum = 2)
static final int DAEMON = 3
FCFS.
Static Protected Member Functions inherited from uvic.disk.Disk
static void open_disk (int startPosition)
static void close_disk ()
static int size_disk ()
static int seek_disk (int block)
static int read_disk ()
static void write_disk (int value)
Detailed Description
The DiskScheduler class acts as a husk class for different disk scheduler implementations.
It provides a basic read/write disk scheduling framework using posix mutex and condition variables to achieve interprocess synchronization. This is not a standalone class and requires extension to achieve full functionality. The insert() and remove() methods must be implemented in order to establish scheduling.
The abstract method deQ must be implemented in order to establish a scheduling order.
Definition at line 22 of file DiskScheduler.java.
Constructor & Destructor Documentation
uvic.disk.DiskScheduler.DiskScheduler (int startPosition) inline
Constructs a Disk class object with specified size and request capacity.
Parameters
liveReq the maximum number of live requests that can be scheduled simultaneously.
blocks the size of the disk in blocks. Each block holds a single block.
Definition at line 62 of file DiskScheduler.java.
References uvic.disk.DiskRequest.enQ().
Member Function Documentation
abstract void uvic.disk.DiskScheduler.insert (DiskRequest dr) protected pure virtual
Inserts a new request into the wait queue.
Derived classes implement this method. The organization of the data structure is defined here.
Referenced by uvic.disk.DiskScheduler.read(), and uvic.disk.DiskScheduler.write().
int uvic.disk.DiskScheduler.read (int position) inline
Reads the specified block into the specified data buffer.
This method blocks until the request is satisfied or an error occurs.
Parameters
position the zero based block number
Definition at line 161 of file DiskScheduler.java.
References uvic.disk.DiskScheduler.insert().
abstract void uvic.disk.DiskScheduler.remove () protected pure virtual
Dequeues the current I/O request and selects the next request for processing.
This method must be implemented by derived classes. The scheduling policy of the disk emulator is derived from this method and the insert method.
void uvic.disk.DiskScheduler.seek (int position) inline protected
This method forces the disk head to seek to the specified position.
Parameters
position zero based block count
Definition at line 268 of file DiskScheduler.java.
Referenced by uvic.disk.DiskScheduler.run().
void uvic.disk.DiskScheduler.showQ () inline protected
debugging method for displaying list of live requests.
WARNING: Be wary of where you cause this. Calling it at the wrong time can cause a seg fault.
Definition at line 312 of file DiskScheduler.java.
References uvic.disk.DiskScheduler.current.
void uvic.disk.DiskScheduler.shutdown () inline
Stops the disk emulator.
Pending requests are cancelled.
Definition at line 115 of file DiskScheduler.java.
References uvic.disk.DiskScheduler.current, and uvic.disk.DiskRequest.deQ().
void uvic.disk.DiskScheduler.spin (int level) inline
Starts the disk emulator.
Processing of disk requests begins.
Definition at line 97 of file DiskScheduler.java.
void uvic.disk.DiskScheduler.write (int position, int value) inline
Writes a block of data at the specified block.
This method blocks until the request is completed or an error occurs.
Parameters
position the zero based block number buffer the data to be written
Definition at line 192 of file DiskScheduler.java.
References uvic.disk.DiskScheduler.insert().
The documentation for this class was generated from the following file:
code/lib-source/uvic/disk/DiskScheduler.java