/*
** simpleRTJ java language core library component.
**
** See the http://www.gnu.org/copyleft/gpl.html for
** details on usage and redistribution of this file.
*/
package java.lang;

/**
 * An Error is a more serious problem that has been generated by the run-time
 * system.
 *
 * For detailed description of this class see the Java language documentation.
 */
public class Error extends Throwable
{
    /**
     * Creates an Error class.
     */
    public Error()
    {
        super();
    }

    /**
     * Creates an Error with the detail message.
     */
    public Error(String s)
    {
        super(s);
    }
}
